"""Add comment to reviews

Revision ID: 194bf47ec119
Revises: 49bc6478744e
Create Date: 2026-04-26 21:46:21.325904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '194bf47ec119'
down_revision: Union[str, Sequence[str], None] = '49bc6478744e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy_drinks_reviews', sa.Column('comment', sa.String(), nullable=True))
    op.create_foreign_key(None, 'energy_drinks_reviews', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'energy_drinks_reviews', 'energy_drinks', ['energy_drink_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'energy_drinks_reviews', type_='foreignkey')
    op.drop_constraint(None, 'energy_drinks_reviews', type_='foreignkey')
    op.drop_column('energy_drinks_reviews', 'comment')
    # ### end Alembic commands ###
