"""Add review model

Revision ID: 26fe06a1206a
Revises: 024226d4692b
Create Date: 2026-10-05 22:30:51.118183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26fe06a1206a'
down_revision: Union[str, Sequence[str], None] = '024226d4692b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('acidity', sa.Float(), nullable=False),
    sa.Column('sweetness', sa.Float(), nullable=False),
    sa.Column('concentration', sa.Float(), nullable=False),
    sa.Column('carbonation', sa.Float(), nullable=False),
    sa.Column('aftertaste', sa.Float(), nullable=False),
    sa.Column('price_quality', sa.Float(), nullable=False),
    sa.Column('overall', sa.Float(), nullable=False),
    sa.Column('energy_drink_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['energy_drink_id'], ['energy_drinks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
