"""Add energy drink model

Revision ID: 42d3fe90270c
Revises: 
Create Date: 2026-04-09 19:26:58.213024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42d3fe90270c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_drinks',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('acidity', sa.Integer(), nullable=False),
    sa.Column('sweetness', sa.Integer(), nullable=False),
    sa.Column('concentration', sa.Integer(), nullable=False),
    sa.Column('carbonation', sa.Integer(), nullable=False),
    sa.Column('aftertaste', sa.Integer(), nullable=False),
    sa.Column('price_quality', sa.Integer(), nullable=False),
    sa.Column('no_sugar', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('acidity >= 1 AND acidity <= 5'),
    sa.CheckConstraint('aftertaste >= 1 AND aftertaste <= 5'),
    sa.CheckConstraint('carbonation >= 1 AND carbonation <= 5'),
    sa.CheckConstraint('concentration >= 1 AND concentration <= 5'),
    sa.CheckConstraint('price_quality >= 1 AND price_quality <= 5'),
    sa.CheckConstraint('sweetness >= 1 AND sweetness <= 5'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('energy_drinks')
    # ### end Alembic commands ###
