"""Add from_admin flag

Revision ID: 49bc6478744e
Revises: e898e6fe222c
Create Date: 2026-04-16 13:06:57.007362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49bc6478744e'
down_revision: Union[str, Sequence[str], None] = 'e898e6fe222c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy_drinks_reviews', sa.Column('from_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('energy_drinks_reviews', 'from_admin')
    # ### end Alembic commands ###
