"""Flatten taste_metrics into separate columns

Revision ID: 53d965618886
Revises: 3d4bf6887c2f
Create Date: 2026-04-10 13:51:03.473773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53d965618886'
down_revision: Union[str, Sequence[str], None] = '3d4bf6887c2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy_drinks', sa.Column('acidity', sa.Integer(), nullable=False))
    op.add_column('energy_drinks', sa.Column('sweetness', sa.Integer(), nullable=False))
    op.add_column('energy_drinks', sa.Column('concentration', sa.Integer(), nullable=False))
    op.add_column('energy_drinks', sa.Column('carbonation', sa.Integer(), nullable=False))
    op.add_column('energy_drinks', sa.Column('aftertaste', sa.Integer(), nullable=False))
    op.add_column('energy_drinks', sa.Column('price_quality', sa.Integer(), nullable=False))
    op.drop_column('energy_drinks', 'taste_metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy_drinks', sa.Column('taste_metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('energy_drinks', 'price_quality')
    op.drop_column('energy_drinks', 'aftertaste')
    op.drop_column('energy_drinks', 'carbonation')
    op.drop_column('energy_drinks', 'concentration')
    op.drop_column('energy_drinks', 'sweetness')
    op.drop_column('energy_drinks', 'acidity')
    # ### end Alembic commands ###
