"""Add favorite drinks

Revision ID: 765f1855b23d
Revises: 78632180e43a
Create Date: 2026-05-24 01:31:28.349386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '765f1855b23d'
down_revision: Union[str, Sequence[str], None] = '78632180e43a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite_drinks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('energy_drink_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['energy_drink_id'], ['energy_drinks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'energy_drink_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_favorite_drinks')
    # ### end Alembic commands ###
