"""Delete role from user model

Revision ID: 7ea8da85add4
Revises: ae3456f86b49
Create Date: 2026-10-10 20:56:50.886354

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ea8da85add4"
down_revision: Union[str, Sequence[str], None] = "ae3456f86b49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("role", sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
