"""Add exclude to created at and updated at

Revision ID: 9e56bce6ea18
Revises: 9bacbe3a31d7
Create Date: 2026-04-11 02:17:57.037092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e56bce6ea18'
down_revision: Union[str, Sequence[str], None] = '9bacbe3a31d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
