"""Add image content type

Revision ID: ae3456f86b49
Revises: ba7fd3b4bd7f
Create Date: 2026-10-08 19:40:39.184973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae3456f86b49'
down_revision: Union[str, Sequence[str], None] = 'ba7fd3b4bd7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy_drinks', sa.Column('image_content_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('energy_drinks', 'image_content_type')
    # ### end Alembic commands ###
