"""Changed image url to image bytes

Revision ID: ba7fd3b4bd7f
Revises: 26fe06a1206a
Create Date: 2026-10-08 00:11:05.355416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba7fd3b4bd7f'
down_revision: Union[str, Sequence[str], None] = '26fe06a1206a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy_drinks', sa.Column('image', sa.LargeBinary(), nullable=True))
    op.drop_column('energy_drinks', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy_drinks', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('energy_drinks', 'image')
    # ### end Alembic commands ###
