"""Fix deprecated backref relationship

Revision ID: dc0e184fe72a
Revises: 49bc6478744e
Create Date: 2026-05-03 13:24:38.112374

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dc0e184fe72a"
down_revision: Union[str, Sequence[str], None] = "49bc6478744e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "energy_drinks_reviews", sa.Column("comment", sa.String(), nullable=True)
    )
    op.create_foreign_key(
        "fk_energy_drinks_reviews_energy_drink_id",
        "energy_drinks_reviews",
        "energy_drinks",
        ["energy_drink_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_energy_drinks_reviews_user_id",
        "energy_drinks_reviews",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE energy_drinks_reviews DROP CONSTRAINT IF EXISTS fk_energy_drinks_reviews_energy_drink_id"
    )
    op.execute(
        "ALTER TABLE energy_drinks_reviews DROP CONSTRAINT IF EXISTS fk_energy_drinks_reviews_user_id"
    )
    op.drop_column("energy_drinks_reviews", "comment")
    # ### end Alembic commands ###
