"""Add review models

Revision ID: e898e6fe222c
Revises: 9da2a9541c5f
Create Date: 2026-04-16 13:01:58.526586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e898e6fe222c'
down_revision: Union[str, Sequence[str], None] = '9da2a9541c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_drinks_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('energy_drink_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('acidity', sa.Float(), nullable=False),
    sa.Column('sweetness', sa.Float(), nullable=False),
    sa.Column('concentration', sa.Float(), nullable=False),
    sa.Column('carbonation', sa.Float(), nullable=False),
    sa.Column('aftertaste', sa.Float(), nullable=False),
    sa.Column('price_quality', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('energy_drinks', 'concentration')
    op.drop_column('energy_drinks', 'carbonation')
    op.drop_column('energy_drinks', 'price_quality')
    op.drop_column('energy_drinks', 'sweetness')
    op.drop_column('energy_drinks', 'aftertaste')
    op.drop_column('energy_drinks', 'acidity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy_drinks', sa.Column('acidity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('energy_drinks', sa.Column('aftertaste', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('energy_drinks', sa.Column('sweetness', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('energy_drinks', sa.Column('price_quality', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('energy_drinks', sa.Column('carbonation', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('energy_drinks', sa.Column('concentration', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('energy_drinks_reviews')
    # ### end Alembic commands ###
