"""Add comment to energy drink add request

Revision ID: ed880269dc03
Revises: d8d282473c13
Create Date: 2026-05-27 13:35:03.523414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed880269dc03'
down_revision: Union[str, Sequence[str], None] = 'd8d282473c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy_drink_add_requests', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('energy_drink_add_requests', 'comment')
    # ### end Alembic commands ###
