"""Add foreign key to requests user_id

Revision ID: ed9e0cbdefad
Revises: 450a1e7241c7
Create Date: 2026-05-26 23:13:50.250685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed9e0cbdefad'
down_revision: Union[str, Sequence[str], None] = '450a1e7241c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'energy_drink_add_requests', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'energy_drink_add_requests', type_='foreignkey')
    # ### end Alembic commands ###
