"""Changed energy drink model

Revision ID: fb40c142f903
Revises: 42d3fe90270c
Create Date: 2026-04-09 21:13:57.700719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb40c142f903'
down_revision: Union[str, Sequence[str], None] = '42d3fe90270c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy_drinks', sa.Column('taste_metrics', sa.JSON(), nullable=False))
    op.drop_constraint(op.f('energy_drinks_name_key'), 'energy_drinks', type_='unique')
    op.drop_column('energy_drinks', 'price_quality')
    op.drop_column('energy_drinks', 'carbonation')
    op.drop_column('energy_drinks', 'acidity')
    op.drop_column('energy_drinks', 'sweetness')
    op.drop_column('energy_drinks', 'concentration')
    op.drop_column('energy_drinks', 'aftertaste')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy_drinks', sa.Column('aftertaste', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('energy_drinks', sa.Column('concentration', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('energy_drinks', sa.Column('sweetness', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('energy_drinks', sa.Column('acidity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('energy_drinks', sa.Column('carbonation', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('energy_drinks', sa.Column('price_quality', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('energy_drinks_name_key'), 'energy_drinks', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('energy_drinks', 'taste_metrics')
    # ### end Alembic commands ###
