"""Add admin comment to add requests

Revision ID: fbbd54e70218
Revises: 17264e7363f0
Create Date: 2026-05-27 22:49:33.715089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbbd54e70218'
down_revision: Union[str, Sequence[str], None] = '17264e7363f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy_drink_add_requests', sa.Column('admin_comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('energy_drink_add_requests', 'admin_comment')
    # ### end Alembic commands ###
